name: bookly
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# update Version
version: 1.0.5+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.5
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/

  # fonts
  fonts:
    - family: GT Sectra Fine Regular
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/gilroy-bold/Gilroy-Bold.ttf
